questions=[
    "What is TypeScript, and how does it differ from JavaScript?",
    "Can you explain the purpose of TypeScript's type annotations?",
    "How do you define a variable with a specific type in TypeScript?",
    "What are the basic data types available in TypeScript?",
    "How do you create an interface in TypeScript?",
    "Can you explain the difference between an interface and a type alias?",
    "How do you implement inheritance in TypeScript?",
    "What is the purpose of the `readonly` modifier in TypeScript?",
    "How do you define a function with specific parameter types and return type in TypeScript?",
    "What are type assertions, and when would you use them?",
    "Can you explain the concept of union types in TypeScript?",
    "How do you handle optional properties in an interface?",
    "What are generics, and how are they used in TypeScript?",
    "How do you create and use a generic function?",
    "What are type guards, and how do they work?",
    "Can you explain the concept of `never` type in TypeScript?",
    "How do you define a tuple type in TypeScript?",
    "What is the `any` type, and why should it be avoided?",
    "How do you create and use enums in TypeScript?",
    "What is the purpose of the `unknown` type?",
    "How do you handle null and undefined values in TypeScript?",
    "Can you explain the difference between `null` and `undefined` in TypeScript?",
    "How do you use the `Partial` utility type?",
    "What are mapped types in TypeScript?",
    "Can you explain the concept of decorators in TypeScript?",
    "How do you create a class with properties and methods in TypeScript?",
    "What is the purpose of the `abstract` class in TypeScript?",
    "How do you implement an interface in a class?",
    "What are access modifiers, and how are they used in TypeScript?",
    "Can you explain the concept of namespaces in TypeScript?",
    "How do you handle module imports and exports in TypeScript?",
    "What is the `keyof` operator, and how is it used?",
    "How do you create and use a type alias?",
    "What are the differences between type aliases and interfaces?",
    "How do you handle function overloading in TypeScript?",
    "What is the purpose of the `as` keyword in TypeScript?",
    "How do you define a constructor in a TypeScript class?",
    "What are the benefits of using TypeScript in a project?",
    "How do you handle type casting in TypeScript?",
    "What are ambient declarations, and when would you use them?",
    "How do you define a constant with a specific type in TypeScript?",
    "What are the differences between `let`, `const`, and `var` in TypeScript?",
    "How do you handle default parameters in TypeScript functions?",
    "What are the benefits of using TypeScript with React?",
    "How do you define a function type in TypeScript?",
    "What is the purpose of the `instanceof` operator in TypeScript?",
    "How do you handle conditional types in TypeScript?",
    "Can you explain the concept of intersection types?",
    "How do you use the `this` keyword in TypeScript classes?",
    "What are index signatures, and how are they used?",
    "How do you define a union type for function parameters?",
    "What is the purpose of the `symbol` type in TypeScript?",
    "How do you handle async/await in TypeScript?",
    "What are the differences between interface and type alias when defining function types?",
    "How do you use the `typeof` operator in TypeScript?",
    "What is the purpose of the `extends` keyword in TypeScript?",
    "How do you create and use a discriminated union?",
    "What are the differences between `interface` and `class` in TypeScript?",
    "How do you define a read-only property in a TypeScript class?",
    "What is the purpose of the `implements` keyword?",
    "How do you handle rest parameters in TypeScript functions?",
    "What are the benefits of using TypeScript with Angular?",
    "How do you use the `in` operator in TypeScript?",
    "What is the purpose of the `super` keyword in TypeScript?",
    "How do you define a method in a TypeScript class?",
    "What are the differences between `abstract` class and interface?",
    "How do you create a type-safe object in TypeScript?",
    "What is the purpose of the `private` access modifier?",
    "How do you use the `public` access modifier in TypeScript?",
    "What are the differences between `protected` and `private` access modifiers?",
    "How do you handle function overloading with different parameter types?",
    "What is the purpose of the `export` keyword in TypeScript?",
    "How do you import a module in TypeScript?",
    "What are the benefits of using TypeScript with Node.js?",
    "How do you handle type compatibility in TypeScript?",
    "What is the purpose of the `declare` keyword in TypeScript?",
    "How do you define a type for an array of objects?",
    "What are the differences between interface and class?",
    "How do you use the `extends` keyword with interfaces?",
    "How do you create and use a generic interface?",
    "What is the purpose of the `static` keyword in TypeScript?",
    "How do you define a type for a promise?",
    "What are the differences between `never` and `void` types?",
    "How do you use the `await` keyword in TypeScript?",
    "How do you handle errors in TypeScript?",
    "What is the purpose of the `global` keyword?",
    "How do you define a type for a callback function?",
    "What are the differences between `enum` and `union` types?",
    "How do you create a type-safe dictionary in TypeScript?",
    "What is the purpose of the `async` keyword?",
    "How do you handle multiple types for a variable?",
    "How do you use the `export default` syntax?",
    "What are the differences between `any` and `unknown` types?",
    "How do you handle nullability in TypeScript?",
    "What is the purpose of the `require` function?",
    "How do you define a type for a complex object?",
    "How do you create and use a generic class?",
    "What are the differences between `const` and `readonly`?",
    "How do you use the `as const` assertion?",
    "What is the purpose of the `module` keyword?",
    "How do you handle type inference in TypeScript?",
    "What are the benefits of using TypeScript with Vue.js?"
]
